GET http://localhost:8000/api/test-checkout
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrZW5uZXRoIGhhcmdpbiIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMTMxNjEyMH0.BaQCRINp_LfnqSlcsD8rbJX2ct-42nTn_zh-hXaenLc

###
POST http://localhost:8000/api/create-checkout
Content-Type: application/json

{
  "booking_id": 2,
  "amount":45
}
###
GET http://localhost:8000/api/Vehicles
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJrZW5uZXRoIGhhcmdpbiIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMTMxNjEyMH0.BaQCRINp_LfnqSlcsD8rbJX2ct-42nTn_zh-hXaenLc 
###
GET http://localhost:8000/api/bookings
###
DELETE http://localhost:8000/api/Vehicles/3
###
POST http://localhost:8000/api/Vehicles
Content-Type: application/json

{
  "rental_rate":100,
  "availability":true
  
}
###

GET http://localhost:8000/api/bookings
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjbGFpcmUiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MjE2NDgzOTB9.XBsULELiap5u-l7i__9QfYg-JtcKCKkbPP8TPw81gxQ
###

POST http://localhost:8000/api/users
Content-Type: application/json
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYXZpZCBzY290dCIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzIwNzk5NDc1fQ.O91aB8TK16dcdKAPB5zOojgqE4T8a9x9p8L5kiHORC8 

{
    "user_id": 5,
    "full_name": "Claire Treasured",
    "email": "claire@gmail.com",
    "contact_phone": "0798257457",
    "address": "Qatar",
    "role": "admin"   
}

###
DELETE http://localhost:8000/api/users/5
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkYXZpZCBzY290dCIsInJvbGUiOiJ1c2VyIiwiZXhwIjoxNzIwNzk5NDc1fQ.O91aB8TK16dcdKAPB5zOojgqE4T8a9x9p8L5kiHORC8 
###


POST http://localhost:8000/api/specifications
Content-Type: application/json
Accept: application/json

{
   "vehicle_id": 5,
    "manufacturer": "Toyota",
    "model": "model 4",
    "year": 2020,
    "fuel_type": "gasoline",
    "engine_capacity": "2.0L",
    "transmission": "automatic",
    "seating_capacity": 7,
    "color": "white",
    "features": "ambient lighting"
    }

###
GET http://localhost:8000/api/test-checkout
Content-Type: application/json

{
 "amount": 2
} 
###

POST http://localhost:8000/api/register 
Content-Type: application/json

{
"userId":2,
"username":"joy" ,
"password":"pass",
"role":"admin"

}
###

POST http://localhost:8000/api/login
Content-Type: application/json

{
"username":"joy" ,
"password":"pass"
 
}


###
POST http://localhost:8000/api/register
Content-Type: application/json

{
"userId":1,
"username":"kenneth hargin" ,
"password":"create!2",
"role":"admin"
  
}
###
POST http://localhost:8000/api/login
Content-Type: application/json

{
"username":"kenneth hargin" ,
"password":"create!2"

}

###
POST http://localhost:8000/api/register
Content-Type: application/json

{
"userId":4,
"username":"lilian keila" ,
"password":"hello98%",
"role":"admin" 
}
###
POST http://localhost:8000/api/login
Content-Type: application/json

{
"username":"lilian keila" ,
"password":"hello98%"
  
}
###
POST http://localhost:8000/api/register
Content-Type: application/json

{
"username":"peter" ,
"password":"113",
"role":"user" ,
"address":"nyeri123",
"fullname":"peter kamau",
"contact_phone":"0787654675",
"email":"peter@gmail.com"

}
###
POST  http://localhost:8000/api/login
Content-Type: application/json

{
  "username":"peter" ,
"password":"113"  
}
###
POST http://localhost:8000/api/register
Content-Type: application/json

{
"username":"joy" ,
"password":"112a",
"role":"admin" ,
"address":"nairobi",
"fullname":"joy wambui",
"contact_phone":"0789675354",
"email":"joy@gmail.com"
}
###
POST http://localhost:8000/api/login
Content-Type: application/json

{
   "username":"joy " ,
   "password":"112a" 
}

###
POST http://localhost:8000/api/register
Content-Type: application/json

{
"userId":5,
"username":"Joy Wambui" ,
"password":"112a",
"role":"admin" 

}
###
POST http://localhost:8000/api/register
Content-Type:application/json

{
"username":"claire" ,
"password":"115",
"role":"admin" ,
"address":"nairobi",
"fullname":"mitchelle claire",
"contact_phone":"0767836542",
"email":"claire@gmail.com"
}
###
POST http://localhost:8000/api/login
Content-Type: application/json

{
  "username":"claire" ,
  "password":"115" 

}

 

